### ISSUE TITLE
Make a well designed page for the image editor

### ISSUE THREAD

**Issue by itaditya** [itaditya/JsImgEditor#1]
Currently the page is ugly as the primary focus was the editing features. Now it would be awesome to make it look much better. You can use Material Design to make this more appealing

**Comment by shivasheeshyadav** [comment]
@itaditya I would like to take up this issue .

**Comment by itaditya** [comment]
@shivasheeshyadav sure go ahead !!

**Comment by heyarviind** [comment]
I'll give it a shot 💯
